import type { Metadata } from "next";
import TextField from "../../../packages/ui/mobile/components/TextField";
import { Radio, RadioGroup } from "../../../packages/ui/mobile/components/Radio";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// 예: apps/mobile-web/app/loan/step1/page.tsx

export default function LoanStep1Page() {
  return (
    <div className="ky-mo-wrap">
      <header className="ky-mo-header">
        <button type="button" className="btn-header-back">
          <span className="ky-hide">뒤로가기</span>
        </button>
        <h1 className="header-title">가계주택담보대출 신청</h1>
        <nav className="nav-warp">
          {/* <button type="button" className="btn-header-home"><span className="ky-hide">홈으로</span></button> */}
          <button type="button" className="btn-header-cancel">
            <span>취소</span>
          </button>
          {/* <button type="button" className="btn-header-menu"><span className="ky-hide">메뉴</span></button> */}
        </nav>
      </header>

      <main className="ky-mo-container" id="main">
        <div className="ky-mo-contents">
          <div className="title-area">
            <nav className="step-wrap" aria-label="진행 단계">
              <h2 className="step-tit">한도조회</h2>
              <ol className="step-num">
                <li className="selected" aria-current="step">
                  <span className="ky-hide">현재 단계: </span>
                  1
                  <span className="ky-hide"> / 총 4단계 중 1단계</span>
                </li>
                <li>
                  <span className="ky-hide">다음 단계: </span>2
                </li>
                <li>3</li>
                <li>4</li>
              </ol>
            </nav>
            <div className="txt-body">고객님의 정보를 알려주세요</div>
          </div>

          <div className="form-area">
            <div className="form-item">
              <div className="label">직업</div>
              <RadioGroup variantClassName="check-type--box" layoutClassName="split-2" roleGroupLabel="직업 선택">
                <Radio name="job" value="직장인" label="직장인" />
                <Radio name="job" value="개인사업자" label="개인사업자" />
              </RadioGroup>
            </div>
            <div className="form-item">
              <TextField
                label="금액"
                placeholder="0"
                inputMode="numeric"
                unitText="원"
                unitLayout="one"
                id="amount"
                error=""
              />
            </div>
            <div className="form-item">
              <TextField
                label="금액"
                placeholder="0"
                inputMode="numeric"
                unitText="원"
                unitLayout="one"
                id="amount1"
                error=""
              />
            </div>
            <div className="form-item">
              <div className="ipt-group">
                <div className="label">자금사용 용도</div>
                <button type="button" className="btn select-box">
                  <span>선택</span>
                </button>
              </div>
            </div>

            <h3 className="tit-h6">주택정보</h3>

            <div className="form-item">
              <div className="label">주택유형</div>
              <div className="check-group check-type--box split-2">
                <div className="check-item">
                  <input
                    type="radio"
                    className="input"
                    id="house-0"
                    name="houseSelect"
                  />
                  <label htmlFor="house-0">아파트(주상복합 포함)</label>
                </div>
                <div className="check-item">
                  <input
                    type="radio"
                    className="input"
                    id="house-1"
                    name="houseSelect"
                  />
                  <label htmlFor="house-1">빌라(연립주택 포함)</label>
                </div>
              </div>
            </div>

            <div className="form-item">
              <div className="ipt-group address">
                <label className="label" htmlFor="iptAddress">
                  주소
                </label>
                <div className="ipt-field">
                  <input
                    type="tel"
                    id="iptAddress"
                    className="ipt-text"
                    placeholder="검색 후 자동입력"
                    readOnly
                  />
                  <button type="button" className="btn-ipt-search">
                    <span>검색</span>
                  </button>
                </div>
                {/* <div className="hint">힌트 메시지</div> */}
              </div>
            </div>

            <div className="form-item">
              <div className="label">담보대출 보유 여부</div>
              <div className="check-group check-type--box split-2">
                <div className="check-item">
                  <input
                    type="radio"
                    className="input"
                    id="rdoSelect-0"
                    name="rdoSelect"
                  />
                  <label htmlFor="rdoSelect-0">네, 있어요</label>
                </div>
                <div className="check-item">
                  <input
                    type="radio"
                    className="input"
                    id="rdoSelect-1"
                    name="rdoSelect"
                  />
                  <label htmlFor="rdoSelect-1">아니오, 없어요</label>
                </div>
              </div>
            </div>

            <div className="form-item">
              <div className="ipt-group">
                <div className="label">명의자</div>
                <button type="button" className="btn select-box">
                  <span>선택</span>
                </button>
              </div>
            </div>

            <div className="form-item">
              <div className="label">거주 여부</div>
              <div className="check-group check-type--box split-2">
                <div className="check-item">
                  <input
                    type="radio"
                    className="input"
                    id="rdoSelect-01"
                    name="rdoSelect1"
                  />
                  <label htmlFor="rdoSelect-01">거주하고 있어요</label>
                </div>
                <div className="check-item">
                  <input
                    type="radio"
                    className="input"
                    id="rdoSelect-11"
                    name="rdoSelect1"
                  />
                  <label htmlFor="rdoSelect-11">세입자가 있어요</label>
                </div>
              </div>
            </div>

            <h3 className="tit-h6">주택정보</h3>

            <div className="form-item">
              <div className="ipt-group">
                <label className="label" htmlFor="iptPhone">
                  휴대폰번호
                </label>
                <div className="ipt-field">
                  <input
                    type="tel"
                    id="iptPhone"
                    className="ipt-text"
                    placeholder="휴대폰번호 입력"
                  />
                </div>
                <div className="hint">힌트 메시지</div>
              </div>
            </div>

            <div className="form-item">
              <div className="ipt-group">
                <label className="label" htmlFor="iptEmail">
                  이메일
                </label>
                <div className="ipt-field">
                  <input
                    type="text"
                    id="iptEmail"
                    className="ipt-text"
                    placeholder="이메일주소 입력"
                  />
                </div>
                <div className="hint">힌트 메시지</div>
              </div>
            </div>
          </div>
        </div>

        <div className="bottom-area">
          <div className="btn-group">
            <button type="button" className="btn btn-pri disabled">
              다음
            </button>
          </div>
        </div>
      </main>
    </div>
  );
}
